name: Build A34 APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Buildozer Action
        uses: kivy/buildozer-action@master
        with:
          save_buildozer_config: false
          buildozer_version: master
