name: AI Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip install buildozer Cython==0.29.33
          sudo apt install -y build-essential libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev zlib1g-dev libgstreamer1.0-dev
      - name: Build with Buildozer
        run: yes | buildozer -v android debug
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: A34-APK
          path: bin/*.apk
